[build]
  base = "spirograph"
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["axios", "form-data", "fs", "path", "multer"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/"
  status = 200
